### PR TITLE
Table Optimisation and Data Presentation Enhancements

### PR DESCRIPTION
**Pull request by msoukhomlinov**
## Description

1. IP Address and Subnet Representation:
* Converted all IP addresses and subnets to CIDR notation for optimised table space usage.

2. Table Generation:
- Implemented a shared function for generating tables across the codebase to make the below-mentioned functionality easier to implement on a mass scale.
- Used a new shared function to generate tables which supports:
a. Removal of empty rows or columns (better use of real estate)
b. (Optional) Custom column widths based on column headings (easy to to set column width)
c. Automatic table width based on columns provided without a need to manually specify width for each column

3. Firewall Policies:
- Policy ID column was added to the firewall policy tables for easier reference.

4. Consistency Improvements:
- Standardised titles for consistency (e.g., "IPSEC phases" and "Administrators").

5. Administrator Trusthosts:
- Enhanced processing of trusthosts for the list of administrators.

6. Interface Display Enhancements:
- Grouped interfaces by type for improved readability.
- Added type-specific column names relevant to each interface category (better use of real estate and provide more relevant info)

7. VLAN Configuration:
- Implemented a new feature to list all configured VLANs.

8. DHCP Server Reporting:
- Improved detection logic for DHCP server configuration.

9. Utility Functions:
- Created a set of private shared utility functions to support the above functionality, including:
a. Subnet mask to CIDR conversion
b. Formatted table writing with advanced features (empty row/column removal, custom column widths)

## Motivation and Context
These changes aim to improve the overall readability, consistency, and efficient use of real estate in the report. They solve the issue of tables being very difficult to read, and removing blank data rows/columns (during the generation of a table) and/or ensuring they contain only relevant columns achieves this outcome.
By standardising on CIDR notation, we reduce space usage and improve readability. 
Enhanced interface and VLAN displays provide easier to read and understand Interface and VLAN information.

## How Has This Been Tested?
Used across a number of Fortigate 7.0.x, 7.2.x and 7.4.x with various combinations of settings.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://www.asbuiltreport.com/about/contributing/) document.

### CODE REVIEW

**Comment by alagoutte** [comment]
Thanks @msoukhomlinov 

Can you split change ? it will be more easy to integrate and review ?

**Comment by msoukhomlinov** [comment]
@alagoutte , are you OK if I split it in this way?

1. Interface Display Enhancements and VLAN Configuration
2. Firewall Policies
3. DHCP Server Reporting
4. Consistency Improvements
5. Administrator Trusthosts
6. Utility Functions with IP Address and Subnet Representation and Table Generation

**Comment by alagoutte** [comment]
> @alagoutte , are you OK if I split it in this way?
> 
>     1. Interface Display Enhancements and VLAN Configuration
> 
>     2. Firewall Policies
> 
>     3. DHCP Server Reporting
> 
>     4. Consistency Improvements
> 
>     5. Administrator Trusthosts
> 
>     6. Utility Functions with IP Address and Subnet Representation and Table Generation

Perfect, it will be more easy to review and integration

**Comment by msoukhomlinov** [comment]
@alagoutte , "1. Interface Display Enhancements and VLAN Configuration" is now under #101 .

**Comment by msoukhomlinov** [comment]
@alagoutte, could you please eye over the "6. Utility Functions with IP Address and Subnet Representation and Table Generation" in here and comment if you'd prefer I pull that into AsBuiltReport.Core repo as it will benefit all projects, not just Fortigate one?

**Comment by alagoutte** [comment]
> @alagoutte, could you please eye over the "6. Utility Functions with IP Address and Subnet Representation and Table Generation" in here and comment if you'd prefer I pull that into AsBuiltReport.Core repo as it will benefit all projects, not just Fortigate one?

Yes, i plan to ask @tpcarman about this idea...

**Comment by alagoutte** [comment]
Hi @msoukhomlinov 

any news about your other change ?

**Pull request closed without merging**
